apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    name: pod-test
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: busybox
      image: busybox
      volumeMounts:
        - mountPath: /shared-data
          name: shared-data
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "echo 'Hello from the debian container' > /shared-data/index.html"
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80 # kubectl port-forward pod/pod-test :80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: shared-data
