apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: partition-test
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
  updateStrategy:
    rollingUpdate:
      partition: 1 # test method: 'kubectl set image statefulset.apps/partition-test nginx=k8s.gcr.io/nginx-slim:0.7'
