apiVersion: v1
kind: Pod
metadata:
  name: shareprocess-test
  labels:
    name: shareprocess-test
spec:
  shareProcessNamespace: true
  hostNetwork: true
  hostIPC: true
  # hostPID: true
  containers:
  - name: nginx
    image: k8s.gcr.io/nginx-slim:0.8
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80 # kubectl port-forward pod/shareprocess-test :80
  - name: busybox # kubectl attach shareprocess-test -c busybox -it
    image: busybox
    stdin: true
    tty: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"