apiVersion: v1
kind: Pod
metadata:
  name: liveness-test
  labels:
    name: liveness-test
    test: liveness
spec:
  containers:
  - name: liveness
    image: busybox
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30s; rm -rf /tmp/healthy; sleep 600s
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 1
