apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    name: website
    app: website
    role: frontend
spec:
  containers:
  - name: website
    image: k8s.gcr.io/nginx-slim:0.8
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
