apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sfs
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        args:
          - /bin/sh
          - -c
          - sleep 1d
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
