apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: http
    name: http
  clusterIP: None # <pod-name>.<svc-name>.<namespace>.svc.cluster.local
