apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-0
  labels:
    tag: pv-test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  storageClassName: standard
  hostPath:
    path: /tmp/pv-test-0 # run 'minikube ssh' to check
