apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  common.cnf: |
      [mysqld]
      default-authentication-plugin=caching_sha2_password
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_ci
      log-bin=mysql-bin
  create_sync_user.sql: |
      CREATE USER '<REPL_USER>'@'%' IDENTIFIED BY '<REPL_PASS>';
      GRANT replication slave,replication client ON *.* TO '<REPL_USER>'@'%';
      FLUSH PRIVILEGES;
  start_slave.sql: |
      CHANGE MASTER TO GET_MASTER_PUBLIC_KEY=1,MASTER_HOST='<MASTER_HOST>',MASTER_USER='<REPL_USER>',MASTER_PASSWORD='<REPL_PASS>';
      START SLAVE;